name: Node.js CI/CD on AWS ubuntu

on: 
  push:
    branches: [ main ]

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: git pull; npm install


    - name: Deploy to AWS EC2
      env: 
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      run: |
        echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${REMOTE_USER}@${REMOTE_HOST}

      # echo "Listing home directory:"
      # ls -la ~
      # uses: appleboy/scp-action@master
      # with:
      #   source: "./"  # This now correctly points to the current directory
      #   target: "/home/ubuntu/testActions"
      #   host: ${{ secrets.REMOTE_HOST }}
      #   username: ${{ secrets.REMOTE_USER }}
      #   key: |
      #     ${{ secrets.SSH_PRIVATE_KEY }}
    
